'use client';

import { useCallback, useEffect, useRef, useState, type CSSProperties, type PointerEvent as ReactPointerEvent } from 'react';
import * as THREE from 'three';

type Place={id:string;name:string;short:string;x:number;z:number;w:number;d:number;h:number;rot:number;color:number;accent:string;action:string;reward:string};
const places:Place[]=[
 {id:'station',name:'JR 武蔵新城駅 南口',short:'武蔵新城駅 南口',x:-3,z:-8,w:50,d:8,h:10,rot:0,color:0xd6d4cc,accent:'#147a62',action:'駅を眺める',reward:'南武線の電車がホームへ入ってきた。'},
 {id:'mac',name:'マクドナルド 武蔵新城店',short:'McDonald’s',x:0,z:41,w:13,d:11,h:23,rot:Math.PI,color:0x24282c,accent:'#ffc72c',action:'ポテトを買う  ¥280',reward:'あつあつのポテトを買った！'},
 {id:'koban',name:'武蔵新城駅前交番',short:'駅前交番',x:29,z:-1,w:8,d:6,h:6,rot:0,color:0xe7e5df,accent:'#2570aa',action:'道を聞く',reward:'お巡りさんが道を教えてくれた。'},
 {id:'izakaya',name:'居酒屋 江戸村',short:'江戸村',x:29,z:17,w:13,d:10,h:11,rot:-Math.PI/2,color:0x4b3028,accent:'#d44d32',action:'江戸村に入る  ¥480',reward:'江戸村でひと休みした！'},
 {id:'massage',name:'マッサージ 楼蘭（江戸村 B1）',short:'↓ 楼蘭 B1',x:23.2,z:19.5,w:3,d:1.2,h:4.2,rot:-Math.PI/2,color:0x41675e,accent:'#b9e1ca',action:'楼蘭で30分  ¥2,000',reward:'足が軽くなった。もう少し歩けそう！'}];
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const mapPins:Record<string,CSSProperties>={station:{left:'38px',top:'4px',bottom:'auto',right:'auto',width:'92px',textAlign:'center'},mac:{left:'67px',top:'123px',bottom:'auto',right:'auto'},koban:{right:'5px',top:'19px',bottom:'auto',left:'auto'},izakaya:{right:'6px',top:'71px',bottom:'auto',left:'auto'},massage:{right:'4px',top:'91px',bottom:'auto',left:'auto'}};

function signTexture(text:string,bg:string,fg='#fff'){
 const c=document.createElement('canvas');c.width=1024;c.height=256;const g=c.getContext('2d')!;g.fillStyle=bg;g.fillRect(0,0,c.width,c.height);g.fillStyle=fg;g.font='bold 92px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(text,512,135);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t;
}
function asphaltTexture(){const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d')!;g.fillStyle='#3d4142';g.fillRect(0,0,512,512);for(let i=0;i<8000;i++){const v=45+Math.random()*35;g.fillStyle=`rgb(${v},${v},${v})`;g.fillRect(Math.random()*512,Math.random()*512,Math.random()*2+.5,Math.random()*2+.5)}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(5,12);t.colorSpace=THREE.SRGBColorSpace;return t}

export default function Home(){
 const mount=useRef<HTMLDivElement>(null),player=useRef({x:0,z:0,a:0}),pitch=useRef(0),keys=useRef(new Set<string>()),drag=useRef<{id:number;x:number;y:number}|null>(null),stick=useRef({x:0,y:0});
 const [nearby,setNearby]=useState<Place|null>(null),[coins,setCoins]=useState(3000),[energy,setEnergy]=useState(72),[toast,setToast]=useState('南口から街歩きをはじめよう'),[visited,setVisited]=useState<string[]>([]),[started,setStarted]=useState(false),[pos,setPos]=useState({x:0,z:0}),[stickUi,setStickUi]=useState({x:0,y:0});
 const interact=useCallback(()=>{if(!nearby)return;const cost=nearby.id==='mac'?280:nearby.id==='izakaya'?480:nearby.id==='massage'?2000:0;if(cost>coins){setToast('コインが足りません');return}setCoins(c=>c-cost);setEnergy(e=>clamp(e+(nearby.id==='massage'?45:nearby.id==='izakaya'?20:nearby.id==='mac'?10:3),0,100));setToast(nearby.reward);setVisited(v=>v.includes(nearby.id)?v:[...v,nearby.id])},[nearby,coins]);
 const moveStick=(e:ReactPointerEvent<HTMLDivElement>)=>{e.preventDefault();e.stopPropagation();const r=e.currentTarget.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),limit=r.width*.34,len=Math.hypot(dx,dy)||1,scale=Math.min(1,limit/len),x=dx*scale,y=dy*scale;stick.current={x:x/limit,y:y/limit};setStickUi({x,y})};
 const resetStick=(e:ReactPointerEvent<HTMLDivElement>)=>{e.preventDefault();e.stopPropagation();stick.current={x:0,y:0};setStickUi({x:0,y:0})};
 useEffect(()=>{const down=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e')interact()},up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[interact]);
 useEffect(()=>{if(location.hostname==='localhost'||location.hostname==='127.0.0.1')return;let checking=false;const assetSignature=(source:Document|string)=>{const urls=typeof source==='string'?[...source.matchAll(/(?:src|href)=["']([^"']+\.(?:js|css)(?:\?[^"']*)?)["']/g)].map(m=>m[1]):[...source.querySelectorAll<HTMLScriptElement|HTMLLinkElement>('script[src],link[rel="stylesheet"][href]')].map(el=>el instanceof HTMLScriptElement?el.src:el.href),normalize=(url:string)=>{try{return new URL(url,location.href).pathname}catch{return url.split('?')[0]}};return [...new Set(urls.map(normalize).filter(url=>url.includes('/_next/static/')||url.includes('/assets/')))].sort().join('|')},currentSignature=assetSignature(document),checkForUpdate=async()=>{if(checking||document.hidden)return;checking=true;try{const separator=location.search?'&':'?',response=await fetch(`${location.pathname}${location.search}${separator}fresh=${Date.now()}`,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!response.ok)return;const latestSignature=assetSignature(await response.text());if(currentSignature&&latestSignature&&latestSignature!==currentSignature)location.reload()}catch{}finally{checking=false}},timer=window.setInterval(checkForUpdate,30000),onVisible=()=>{if(!document.hidden)void checkForUpdate()};document.addEventListener('visibilitychange',onVisible);return()=>{window.clearInterval(timer);document.removeEventListener('visibilitychange',onVisible)}},[]);
 useEffect(()=>{if(!mount.current)return;const host=mount.current,scene=new THREE.Scene();scene.background=new THREE.Color(0xcfe8f2);scene.fog=new THREE.FogExp2(0xd5e8ee,.009);
 const camera=new THREE.PerspectiveCamera(68,host.clientWidth/host.clientHeight,.1,160);camera.position.set(0,2.25,10);
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.appendChild(renderer.domElement);
 scene.add(new THREE.HemisphereLight(0xe5edf0,0x424844,2.45));const sun=new THREE.DirectionalLight(0xfff6e8,2.7);sun.position.set(-22,42,-18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-45;sun.shadow.camera.right=45;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;scene.add(sun);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(110,90),new THREE.MeshStandardMaterial({color:0xbca483,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.set(0,-.02,20);ground.receiveShadow=true;scene.add(ground);
 const roadMat=new THREE.MeshStandardMaterial({map:asphaltTexture(),roughness:.93,metalness:.03});
 const roadBaseMat=new THREE.MeshStandardMaterial({color:0xbca483,roughness:.98});const road=new THREE.Mesh(new THREE.PlaneGeometry(78,65),roadBaseMat);road.rotation.x=-Math.PI/2;road.position.set(0,.025,20);road.receiveShadow=true;scene.add(road);
 const sideMat=new THREE.MeshStandardMaterial({color:0xbca483,roughness:.96});
 const addApron=(points:Array<[number,number]>,bay:{x:number;z:number;rx:number;rz:number;rotation:number})=>{const shape=new THREE.Shape();points.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();const hole=new THREE.Path();hole.absellipse(bay.x,-bay.z,bay.rx,bay.rz,0,Math.PI*2,true,-bay.rotation);shape.holes.push(hole);const mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape,32),sideMat);mesh.rotation.x=-Math.PI/2;mesh.position.y=.055;mesh.receiveShadow=true;scene.add(mesh)};
 const addWalkwaySegment=(ax:number,az:number,bx:number,bz:number,width:number)=>{const dx=bx-ax,dz=bz-az,length=Math.hypot(dx,dz),deck=new THREE.Mesh(new THREE.BoxGeometry(width,.045,length),sideMat);deck.position.set((ax+bx)/2,.064,(az+bz)/2);deck.rotation.y=Math.atan2(dx,dz);deck.receiveShadow=true;scene.add(deck);for(const [x,z] of [[ax,az],[bx,bz]]){const cap=new THREE.Mesh(new THREE.CylinderGeometry(width/2,width/2,.046,32),sideMat);cap.position.set(x,.064,z);cap.receiveShadow=true;scene.add(cap)}};
 const addRoadRibbon=(coords:Array<[number,number]>,width:number)=>{const curve=new THREE.CatmullRomCurve3(coords.map(([x,z])=>new THREE.Vector3(x,0,z)),false,'centripetal'),samples=curve.getPoints(36),left:Array<[number,number]>=[],right:Array<[number,number]>=[];samples.forEach((p,i)=>{const before=samples[Math.max(0,i-1)],after=samples[Math.min(samples.length-1,i+1)],dx=after.x-before.x,dz=after.z-before.z,length=Math.hypot(dx,dz)||1,nx=-dz/length,nz=dx/length;left.push([p.x+nx*width/2,p.z+nz*width/2]);right.push([p.x-nx*width/2,p.z-nz*width/2])});const shape=new THREE.Shape();left.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));right.reverse().forEach(([x,z])=>shape.lineTo(x,-z));shape.closePath();const ribbon=new THREE.Mesh(new THREE.ShapeGeometry(shape,24),roadMat);ribbon.rotation.x=-Math.PI/2;ribbon.position.y=.057;ribbon.receiveShadow=true;scene.add(ribbon);for(const [x,z] of [coords[0],coords[coords.length-1]]){const cap=new THREE.Mesh(new THREE.CircleGeometry(width/2,40),roadMat);cap.rotation.x=-Math.PI/2;cap.position.set(x,.058,z);cap.receiveShadow=true;scene.add(cap)}};
 addApron([[-27,-3],[-9,-3],[-7,22],[-17,27],[-22,9],[-27,6]],{x:-14,z:12.5,rx:4.7,rz:9.8,rotation:-.3});
 addApron([[5,-3],[23,-3],[23,5],[8,25],[4,25]],{x:11.5,z:9.5,rx:5.9,rz:5,rotation:.12});
 const stationWalkway=new THREE.Mesh(new THREE.BoxGeometry(8.5,.045,27.9),sideMat);stationWalkway.position.set(0,.064,10);stationWalkway.receiveShadow=true;scene.add(stationWalkway);
 addWalkwaySegment(0,33.8,21,33.8,6.6);addWalkwaySegment(21,33.8,21,16.7,4.2);
 addRoadRibbon([[-32,25],[-24,25.5],[-15.5,26.6],[-8.5,27],[-4,26.3]],5.6);
 addRoadRibbon([[4,26.3],[7.5,23.5],[9,19],[10,14]],6);
 addRoadRibbon([[14.5,7.5],[18,6],[22,4.2],[28,4],[35,4.5]],6);
 const addCrosswalk=(x:number,z:number,w:number,d:number,rotation=0,landingAxis:'x'|'z'='z')=>{const group=new THREE.Group(),roadSurface=new THREE.Mesh(new THREE.BoxGeometry(w+.6,.035,d+.25),new THREE.MeshStandardMaterial({color:0x515657,roughness:.95})),stripeMat=new THREE.MeshStandardMaterial({color:0xf5f3eb,roughness:.72}),landingDepth=1.8;roadSurface.position.y=.068;roadSurface.receiveShadow=true;group.add(roadSurface);for(const direction of [-1,1]){const landing=landingAxis==='x'?new THREE.Mesh(new THREE.BoxGeometry(landingDepth,.04,d+1.2),sideMat):new THREE.Mesh(new THREE.BoxGeometry(w+1.2,.04,landingDepth),sideMat);landing.position.set(landingAxis==='x'?direction*(w/2+landingDepth/2):0,.075,landingAxis==='z'?direction*(d/2+landingDepth/2):0);landing.receiveShadow=true;group.add(landing)}for(let offset=-d/2+.36;offset<d/2;offset+=.92){const stripe=new THREE.Mesh(new THREE.BoxGeometry(w,.035,.48),stripeMat);stripe.position.set(0,.095,offset);group.add(stripe)}group.position.set(x,0,z);group.rotation.y=rotation;scene.add(group)};
 addCrosswalk(-24.5,-1.2,7,4.8);addCrosswalk(0,26.3,8.5,4.8);addCrosswalk(-15.5,26.6,7.5,4.6,Math.PI/2-.12,'x');addCrosswalk(25.5,-1.2,7,4.8);
 const makeBox=(w:number,h:number,d:number,color:number)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.72,metalness:.03}));m.castShadow=m.receiveShadow=true;return m};
 const glassMaterial=()=>new THREE.MeshPhysicalMaterial({color:0x88aab6,roughness:.14,metalness:.22,transmission:.16,clearcoat:1});
 const addSign=(group:THREE.Group,text:string,w:number,h:number,y:number,z:number,bg:string,fg='#fff')=>{const sign=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshStandardMaterial({map:signTexture(text,bg,fg),roughness:.48,emissive:0xffffff,emissiveIntensity:.12}));sign.position.set(0,y,z);group.add(sign);return sign};
 const addWindowGrid=(group:THREE.Group,w:number,h:number,y:number,z:number,columns=3)=>{const glass=makeBox(w,h,.12,0x759aa4);glass.material=glassMaterial();glass.position.set(0,y,z);group.add(glass);const frameMat=new THREE.MeshStandardMaterial({color:0xd7dcda,roughness:.45,metalness:.3});for(let i=1;i<columns;i++){const frame=new THREE.Mesh(new THREE.BoxGeometry(.12,h+.08,.18),frameMat);frame.position.set(-w/2+w*i/columns,y,z+.08);group.add(frame)}for(const offset of [-h/2,h/2]){const frame=new THREE.Mesh(new THREE.BoxGeometry(w+.12,.11,.18),frameMat);frame.position.set(0,y+offset,z+.08);group.add(frame)}};
 const environmentObstacles:Array<{x:number;z:number;w:number;d:number}>=[];
 const treePositions:Array<{x:number;z:number}>=[],islandObstacles:Array<{x:number;z:number;rx:number;rz:number;rotation:number}>=[],trunkMat=new THREE.MeshStandardMaterial({color:0x5b4434,roughness:1}),leafMat=new THREE.MeshStandardMaterial({color:0x477443,roughness:.94}),islandCurbMat=new THREE.MeshStandardMaterial({color:0xd6cdbd,roughness:.9}),grassMat=new THREE.MeshStandardMaterial({color:0x658d55,roughness:1});
 const addTransitBay=(x:number,z:number,sx:number,sz:number,rotation:number,label:string)=>{const asphalt=new THREE.Mesh(new THREE.CircleGeometry(1,64),roadMat);asphalt.scale.set(sx,sz,1);asphalt.rotation.set(-Math.PI/2,0,-rotation);asphalt.position.set(x,.058,z);asphalt.receiveShadow=true;scene.add(asphalt);const ring=new THREE.Mesh(new THREE.RingGeometry(.94,1,64),new THREE.MeshStandardMaterial({color:0x7d8282,roughness:.9}));ring.scale.set(sx,sz,1);ring.rotation.set(-Math.PI/2,0,-rotation);ring.position.set(x,.071,z);scene.add(ring);const mark=new THREE.Mesh(new THREE.PlaneGeometry(sx*1.25,sz*.45),new THREE.MeshStandardMaterial({map:signTexture(label,'#454a4b','#f5f2dc'),roughness:.9}));mark.rotation.set(-Math.PI/2,0,-rotation);mark.position.set(x,.073,z);scene.add(mark)};
 const addLandscapeIsland=(x:number,z:number,sx:number,sz:number,rotation:number,trees:Array<[number,number]>)=>{const curb=new THREE.Mesh(new THREE.CylinderGeometry(1.08,1.08,.16,48),islandCurbMat);curb.scale.set(sx,1,sz);curb.position.set(x,.13,z);curb.rotation.y=rotation;curb.receiveShadow=true;scene.add(curb);const grass=new THREE.Mesh(new THREE.CylinderGeometry(1,1,.18,48),grassMat);grass.scale.set(sx,1,sz);grass.position.set(x,.22,z);grass.rotation.y=rotation;grass.receiveShadow=true;scene.add(grass);islandObstacles.push({x,z,rx:sx,rz:sz,rotation});for(const [lx,lz] of trees){const tx=x+Math.cos(rotation)*lx+Math.sin(rotation)*lz,tz=z-Math.sin(rotation)*lx+Math.cos(rotation)*lz;treePositions.push({x:tx,z:tz});const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.14,.2,2.7,10),trunkMat);trunk.position.set(tx,1.62,tz);trunk.castShadow=true;scene.add(trunk);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(1.05,2),leafMat);crown.position.set(tx,3.45,tz);crown.scale.y=1.16;crown.castShadow=true;scene.add(crown)}};
 addTransitBay(-14,12.5,4.7,9.8,-.3,'BUS');addTransitBay(11.5,9.5,5.9,5,.12,'TAXI');
 addLandscapeIsland(-14,12.5,2.25,6.2,-.3,[[0,-3.3],[.25,0],[-.2,3.25]]);addLandscapeIsland(11.5,9.5,2.8,2.25,.12,[[-1,0],[1,0]]);
 for(const q of places){
  const group=new THREE.Group(),front=q.d/2+.08;
  if(q.id==='station'){
   const deck=makeBox(q.w,2.1,q.d,0x999a96);deck.position.y=8;group.add(deck);const parapet=makeBox(q.w,1.3,q.d+.6,0xb2b2ad);parapet.position.y=9.65;group.add(parapet);
   for(const x of [-11,-3.7,3.7,11]){const pillar=makeBox(1.35,7.3,2.1,0xa5a49d);pillar.position.set(x,3.65,0);group.add(pillar)}
   const exit=makeBox(10,5.4,2.6,0xe1e2df);exit.position.set(-5.5,2.7,front-1.15);group.add(exit);addWindowGrid(group,6.5,2.2,2.4,front+.03,3);addSign(group,'JR 武蔵新城駅 南口',11,1.25,5.65,front+.08,'#f5f4ef','#185f50');
   const canopy=new THREE.Mesh(new THREE.CylinderGeometry(2.15,2.15,8.5,20,1,false,0,Math.PI),new THREE.MeshStandardMaterial({color:0x8b8578,roughness:.58,metalness:.45,side:THREE.DoubleSide}));canopy.rotation.z=Math.PI/2;canopy.rotation.y=Math.PI/2;canopy.position.set(-5.5,4.3,front+1.1);group.add(canopy);
  }else if(q.id==='mac'){
   const body=makeBox(q.w,q.h,q.d,0x25292d);body.position.y=q.h/2;group.add(body);
   const redBand=makeBox(q.w*.86,.48,.28,0xb02b24);redBand.position.set(0,3.45,front+.08);group.add(redBand);addSign(group,"McDonald's",q.w*.82,1.25,5.05,front+.1,'#25292d','#f3f3ee');
   for(const y of [8.1,12.25,16.4])addWindowGrid(group,q.w*.82,3.1,y,front+.04,4);
   const storefront=makeBox(q.w*.72,2.8,.14,0x607b83);storefront.material=glassMaterial();storefront.position.set(-.7,1.55,front+.08);group.add(storefront);for(const x of [-4.4,-1.5,1.4,4.3]){const mullion=makeBox(.12,2.9,.22,0xd6dcda);mullion.position.set(x,1.55,front+.19);group.add(mullion)}
   const arch=addSign(group,'M',2.6,2.35,19.15,front+.11,'#25292d','#ffc72c');arch.position.x=-3.8;
   const billboard=makeBox(q.w*.92,3.35,.32,0x26334f);billboard.position.set(0,21.1,front+.12);group.add(billboard);for(let i=0;i<8;i++){const fry=makeBox(.38,2.35+Math.sin(i)*.6,.25,0xf6c343);fry.position.set(-2.3+i*.68,21.25+Math.cos(i*.8)*.25,front+.35);fry.rotation.z=(i-3.5)*.045;group.add(fry)}
   const sideArch=addSign(group,'M',2.15,1.9,4.3,front+1.05,'#c32f28','#ffc72c');sideArch.position.x=q.w*.48;sideArch.rotation.y=-Math.PI/2;
  }else if(q.id==='koban'){
   const body=makeBox(q.w,q.h,q.d,0xe3e4e2);body.position.y=q.h/2;group.add(body);addWindowGrid(group,q.w*.72,2.25,2.25,front+.05,3);addSign(group,'交番  KOBAN',q.w*.76,.85,4.85,front+.1,'#f2f3f1','#28658b');
   const canopy=new THREE.Mesh(new THREE.CylinderGeometry(1.45,1.45,4.5,18,1,false,0,Math.PI),new THREE.MeshStandardMaterial({color:0x817b6b,roughness:.48,metalness:.5,side:THREE.DoubleSide}));canopy.rotation.z=Math.PI/2;canopy.rotation.y=Math.PI/2;canopy.position.set(-.8,3.2,front+.65);group.add(canopy);
  }else if(q.id==='izakaya'){
   const body=makeBox(q.w,q.h,q.d,0x34383a);body.position.y=q.h/2;group.add(body);const lower=makeBox(q.w*.82,3.7,.18,0x252728);lower.position.set(0,1.85,front+.04);group.add(lower);addSign(group,'大衆酒場  江戸村',q.w*.9,1.35,7.15,front+.12,'#f2eee3','#292421');
   for(const x of [-3.5,0,3.5]){const lantern=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.62,4,10),new THREE.MeshStandardMaterial({color:0xd94a35,emissive:0x9f1c12,emissiveIntensity:.32}));lantern.position.set(x,4.65,front+.58);group.add(lantern)}addWindowGrid(group,q.w*.65,1.8,9.45,front+.04,3);
   const blade=addSign(group,'串焼',1.35,3.35,8.2,front+1.15,'#f4efe3','#292421');blade.position.x=q.w*.47;blade.rotation.y=-Math.PI/2;
  }else{
   const opening=makeBox(q.w,3.2,q.d+.8,0x171b1b);opening.position.y=1.6;group.add(opening);addSign(group,'楼蘭  B1',q.w*1.45,.8,4.15,front+.65,'#315d56','#e8f5ee');for(let i=0;i<5;i++){const step=makeBox(q.w*.8,.16,.42,0x777b76);step.position.set(0,.18+i*.22,front+.45-i*.25);group.add(step)}
  }
  group.position.set(q.x,0,q.z);group.rotation.y=q.rot;scene.add(group);
 }
 const woman=new THREE.Group(),skinMat=new THREE.MeshStandardMaterial({color:0xd8a17d,roughness:.82}),hairMat=new THREE.MeshStandardMaterial({color:0x593a29,roughness:.9}),blouseMat=new THREE.MeshStandardMaterial({color:0xe9e2d8,roughness:.78}),skirtMat=new THREE.MeshStandardMaterial({color:0x29313d,roughness:.76}),shoeMat=new THREE.MeshStandardMaterial({color:0x242125,roughness:.7}),metalMat=new THREE.MeshStandardMaterial({color:0xb8bec3,roughness:.28,metalness:.78}),screenMat=new THREE.MeshStandardMaterial({color:0x10161d,roughness:.18,metalness:.18,emissive:0x18354e,emissiveIntensity:.25});
 const addWomanPart=(geometry:THREE.BufferGeometry,material:THREE.Material,x:number,y:number,z:number)=>{const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=true;woman.add(mesh);return mesh};
 const addArm=(from:THREE.Vector3,to:THREE.Vector3)=>{const delta=to.clone().sub(from),arm=addWomanPart(new THREE.CylinderGeometry(.075,.085,delta.length(),8),skinMat,(from.x+to.x)/2,(from.y+to.y)/2,(from.z+to.z)/2);arm.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize())};
 for(const x of [-.16,.16]){addWomanPart(new THREE.CylinderGeometry(.095,.12,.9,9),skinMat,x,.54,0);const shoe=addWomanPart(new THREE.BoxGeometry(.24,.14,.38),shoeMat,x,.09,.08);shoe.rotation.x=-.08}
 addWomanPart(new THREE.CylinderGeometry(.28,.43,.48,12),skirtMat,0,1.13,0);addWomanPart(new THREE.BoxGeometry(.58,.68,.3),blouseMat,0,1.61,0);addWomanPart(new THREE.CylinderGeometry(.09,.1,.13,9),skinMat,0,2,0);addWomanPart(new THREE.SphereGeometry(.29,18,14),skinMat,0,2.22,0);
 const hairBack=addWomanPart(new THREE.CapsuleGeometry(.3,.77,5,12),hairMat,0,1.93,-.18);hairBack.scale.set(1.04,1,0.72);addWomanPart(new THREE.SphereGeometry(.305,18,12,0,Math.PI*2,0,Math.PI*.58),hairMat,0,2.27,-.02);
 for(const x of [-.155,.155])addWomanPart(new THREE.TorusGeometry(.13,.018,7,18),metalMat,x,2.25,.272);const bridge=addWomanPart(new THREE.BoxGeometry(.08,.025,.025),metalMat,0,2.25,.272);bridge.rotation.z=.02;
 addArm(new THREE.Vector3(-.29,1.78,.02),new THREE.Vector3(-.11,1.46,.39));addArm(new THREE.Vector3(.29,1.78,.02),new THREE.Vector3(.11,1.46,.39));
 const phoneBody=addWomanPart(new THREE.BoxGeometry(.3,.52,.065),metalMat,0,1.48,.48),phoneScreen=addWomanPart(new THREE.BoxGeometry(.26,.45,.018),screenMat,0,1.48,.518);phoneBody.rotation.x=phoneScreen.rotation.x=-.18;const cameraLens=addWomanPart(new THREE.CylinderGeometry(.027,.027,.012,12),screenMat,-.09,1.67,.446);cameraLens.rotation.x=Math.PI/2;
 woman.position.set(20.8,0,19.45);woman.rotation.y=-Math.PI/2;scene.add(woman);environmentObstacles.push({x:20.8,z:19.45,w:.8,d:.8});
 const lawson=new THREE.Group(),lawsonBody=makeBox(11,9,10,0xe5e5e1);lawsonBody.position.y=4.5;lawson.add(lawsonBody);const lawsonFront=makeBox(10.1,3.25,.18,0x65878f);lawsonFront.material=glassMaterial();lawsonFront.position.set(0,1.8,5.08);lawson.add(lawsonFront);addSign(lawson,'LAWSON',10.2,1.15,5.15,5.16,'#f7f7f2','#2673b8');const lawsonBand=makeBox(10.2,.26,.25,0x2b79bd);lawsonBand.position.set(0,4.38,5.16);lawson.add(lawsonBand);lawson.position.set(-31,0,18);lawson.rotation.y=Math.PI/2;scene.add(lawson);environmentObstacles.push({x:-31,z:18,w:10,d:11});
 const fillerSpecs=[{x:-28,z:36,w:14,d:12,h:16,c:0x777b7b},{x:12,z:47,w:8,d:12,h:25,c:0xc0c3c1},{x:39,z:18,w:10,d:34,h:15,c:0x9b9e9b}];for(const b of fillerSpecs){const building=makeBox(b.w,b.h,b.d,b.c);building.position.set(b.x,b.h/2,b.z);scene.add(building);environmentObstacles.push({x:b.x,z:b.z,w:b.w,d:b.d});for(let y=4;y<b.h-1;y+=3.4){const windows=makeBox(b.w*.68,1.45,.1,0x769096);windows.material=glassMaterial();windows.position.set(b.x,y,b.z-b.d/2-.06);scene.add(windows)}}
 const blocked=(x:number,z:number)=>{const radius=.62;for(const q of places){const quarterTurn=Math.abs(Math.sin(q.rot))>.5,halfX=(quarterTurn?q.d:q.w)/2+radius,halfZ=(quarterTurn?q.w:q.d)/2+radius;if(Math.abs(x-q.x)<halfX&&Math.abs(z-q.z)<halfZ)return true}for(const o of environmentObstacles)if(Math.abs(x-o.x)<o.w/2+radius&&Math.abs(z-o.z)<o.d/2+radius)return true;for(const island of islandObstacles){const dx=x-island.x,dz=z-island.z,lx=Math.cos(island.rotation)*dx-Math.sin(island.rotation)*dz,lz=Math.sin(island.rotation)*dx+Math.cos(island.rotation)*dz;if((lx/(island.rx+radius))**2+(lz/(island.rz+radius))**2<1)return true}for(const t of treePositions)if(Math.hypot(x-t.x,z-t.z)<.9)return true;return false};
 const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};window.addEventListener('resize',resize);let frame=0,last=performance.now(),uiTick=0,energyTick=0;
 const animate=(now:number)=>{const dt=Math.min((now-last)/1000,.04);last=now;const p=player.current,k=keys.current,j=stick.current,keyboardForward=(k.has('w')||k.has('arrowup')?1:0)-(k.has('s')||k.has('arrowdown')?1:0),turn=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0),rawForward=keyboardForward-j.y,rawStrafe=-j.x,magnitude=Math.max(1,Math.hypot(rawForward,rawStrafe)),forward=rawForward/magnitude,strafe=rawStrafe/magnitude,joystickSpeed=1+Math.min(1,Math.hypot(j.x,j.y));p.a-=turn*dt*1.75;const step=6.2*dt*joystickSpeed,nx=clamp(p.x+(Math.sin(p.a)*forward+Math.cos(p.a)*strafe)*step,-38,36),nz=clamp(p.z+(Math.cos(p.a)*forward-Math.sin(p.a)*strafe)*step,-2.5,52);if(!blocked(nx,p.z))p.x=nx;if(!blocked(p.x,nz))p.z=nz;camera.position.set(p.x,2.25,p.z);const cp=Math.cos(pitch.current);camera.lookAt(p.x+Math.sin(p.a)*cp*10,2.25+Math.sin(pitch.current)*10,p.z+Math.cos(p.a)*cp*10);if(Math.abs(forward)+Math.abs(strafe)>.05){energyTick+=dt;if(energyTick>2.2){setEnergy(e=>clamp(e-1,0,100));energyTick=0}}uiTick+=dt;if(uiTick>.12){uiTick=0;setPos({x:p.x,z:p.z});const close=places.filter(q=>q.id!=='station').sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];setNearby(Math.hypot(close.x-p.x,close.z-p.z)<8?close:null)}renderer.render(scene,camera);frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);
 return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',resize);renderer.dispose();renderer.domElement.remove();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{const mm=m as THREE.MeshStandardMaterial;mm.map?.dispose();m.dispose()})}})}},[]);
 return <main className="game-shell"><div ref={mount} className="world" aria-label="武蔵新城駅前の3D街歩き画面" onPointerDown={e=>{drag.current={id:e.pointerId,x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current?.id===e.pointerId){player.current.a-=(e.clientX-drag.current.x)*.006;pitch.current=clamp(pitch.current-(e.clientY-drag.current.y)*.0045,-.82,.82);drag.current={id:e.pointerId,x:e.clientX,y:e.clientY}}}} onPointerUp={e=>{if(drag.current?.id===e.pointerId)drag.current=null}} onPointerCancel={()=>drag.current=null}/>
 {started&&<><div className="joystick-wrap" aria-label="移動スティック" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);moveStick(e)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))moveStick(e)}} onPointerUp={resetStick} onPointerCancel={resetStick}><span className="joystick-ring"/><span className="joystick-knob" style={{transform:`translate(${stickUi.x}px, ${stickUi.y}px)`}}/><small>移動</small></div><div className="look-hint">画面をドラッグして見回す</div></>}
 <header className="topbar"><div className="brand"><span className="brand-mark">新</span><div><b>しんじょう さんぽ</b><small>武蔵新城 南口エリア・3D</small></div></div><div className="stats"><span>🪙 <b>{coins.toLocaleString()}</b></span><span>元気 <i><em style={{width:`${energy}%`}}/></i></span></div></header>
 <aside className="quest-card"><p className="eyebrow">TODAY&apos;S WALK</p><h1>南口の4スポットをめぐろう</h1><div className="progress"><span style={{width:`${visited.length/4*100}%`}}/></div><p>{visited.length} / 4 スポット</p><ul>{places.slice(1,5).map(q=><li key={q.id} className={visited.includes(q.id)?'done':''}><span>{visited.includes(q.id)?'✓':'○'}</span>{q.short}</li>)}</ul></aside>
 <aside className="map-card" aria-label="ミニマップ"><div className="map-title"><b>武蔵新城駅 南口</b><span>N ↑</span></div><div className="mini-map"><div className="rail"/><div className="map-road map-road-left"/><div className="map-road map-road-taxi"/><div className="map-road map-road-koban"/><div className="map-walkway"/><div className="map-walkway-edumura"/><div className="map-walkway-lawson"/><div className="map-apron map-apron-bus"/><div className="map-apron map-apron-taxi"/><div className="map-transit map-bus">BUS</div><div className="map-transit map-taxi">TAXI</div><div className="map-crosswalk map-crosswalk-left"/><div className="map-crosswalk map-crosswalk-bottom-left"/><div className="map-crosswalk map-crosswalk-center"/><div className="map-crosswalk map-crosswalk-right"/><span className="pin pin-lawson">LAWSON</span>{places.map(q=><span key={q.id} className={`pin pin-${q.id}`} style={mapPins[q.id]} title={q.name}>{q.short}</span>)}<span className="you" style={{left:`${clamp(50+pos.x*1.22,3,95)}%`,top:`${clamp(13+pos.z*2.55,3,94)}%`}}>▲</span></div></aside>
 <div className="toast" role="status">{toast}</div>{nearby&&<section className="action-card"><div><small>近くのスポット</small><b>{nearby.name}</b></div><button onClick={interact}><kbd>E</kbd>{nearby.action}</button></section>}<div className="controls"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> 歩く</span><span>ドラッグ 見回す</span><span><kbd>E</kbd> 入る / 調べる</span></div>
 {!started&&<div className="intro"><div className="intro-panel"><p className="eyebrow">THREE.JS STREET WALK</p><h2>南口の街を、<br/><em>本物の3Dで。</em></h2><p>南口を出て正面のマクドナルドへ。手前の角を左へ曲がると、左に駅前交番、右に江戸村。その地下には楼蘭があります。</p><button onClick={()=>setStarted(true)}>南口からスタート <span>→</span></button><small>WebGL 3Dグラフィックス版</small></div></div>}</main>
}
