'use client';

import { useCallback, useEffect, useRef, useState } from 'react';

type Place = { id:string; name:string; short:string; x:number; z:number; w:number; h:number; color:string; accent:string; action:string; reward:string };
const places:Place[]=[
{id:'station',name:'JR 武蔵新城駅',short:'北口',x:0,z:18,w:11,h:6,color:'#e9e6df',accent:'#2c8b73',action:'駅を眺める',reward:'南武線の電車がホームへ入ってきた。'},
{id:'mac',name:'マクドナルド 武蔵新城店',short:'McD',x:-12,z:-4,w:8,h:10,color:'#8f211d',accent:'#ffc72c',action:'ポテトを買う  ¥280',reward:'あつあつのポテトを買った！'},
{id:'koban',name:'武蔵新城駅前交番',short:'交番',x:11,z:1,w:5,h:5,color:'#f2f0e8',accent:'#2975b9',action:'道を聞く',reward:'お巡りさんが商店街への道を教えてくれた。'},
{id:'izakaya',name:'駅前餃子酒場',short:'酒場',x:6,z:-12,w:9,h:8,color:'#3c2720',accent:'#f05a3e',action:'餃子を食べる  ¥480',reward:'焼きたて餃子で元気になった！'},
{id:'massage',name:'地下のリラクゼーション',short:'B1',x:6,z:-15,w:7,h:3,color:'#385a52',accent:'#b9e1ca',action:'30分休む  ¥2,000',reward:'足が軽くなった。もう少し歩けそう！'},
{id:'river',name:'小さな眺めスポット',short:'景色',x:-15,z:-23,w:7,h:3,color:'#477c70',accent:'#bce5dd',action:'景色を楽しむ',reward:'風が気持ちいい。街の音が少し遠くなった。'}];
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));

export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null), player=useRef({x:0,z:9,a:Math.PI}), keys=useRef(new Set<string>()), drag=useRef<number|null>(null);
 const [nearby,setNearby]=useState<Place|null>(null),[coins,setCoins]=useState(3000),[energy,setEnergy]=useState(72),[toast,setToast]=useState('北口から街歩きをはじめよう'),[visited,setVisited]=useState<string[]>([]),[started,setStarted]=useState(false);
 const interact=useCallback(()=>{if(!nearby)return;const cost=nearby.id==='mac'?280:nearby.id==='izakaya'?480:nearby.id==='massage'?2000:0;if(cost>coins){setToast('コインが足りません');return}setCoins(c=>c-cost);setEnergy(e=>clamp(e+(nearby.id==='massage'?45:nearby.id==='izakaya'?20:nearby.id==='mac'?10:3),0,100));setToast(nearby.reward);setVisited(v=>v.includes(nearby.id)?v:[...v,nearby.id])},[nearby,coins]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e')interact()},up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[interact]);
 useEffect(()=>{const canvas=canvasRef.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;let frame=0,last=performance.now(),energyTick=0;
 const project=(wx:number,wz:number,wh=0)=>{const p=player.current,dx=wx-p.x,dz=wz-p.z,ca=Math.cos(p.a),sa=Math.sin(p.a),side=dx*ca-dz*sa,depth=dx*sa+dz*ca,scale=canvas.width*.78/Math.max(depth,.1);return{x:canvas.width/2+side*scale,y:canvas.height*.53-wh*scale,depth,scale}};
 const draw=(now:number)=>{const dt=Math.min((now-last)/1000,.04);last=now;const p=player.current,k=keys.current,dir=(k.has('w')||k.has('arrowup')?1:0)-(k.has('s')||k.has('arrowdown')?1:0),turn=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0);p.a+=turn*dt*1.8;p.x+=Math.sin(p.a)*dir*dt*6;p.z+=Math.cos(p.a)*dir*dt*6;p.x=clamp(p.x,-20,20);p.z=clamp(p.z,-27,15);if(dir){energyTick+=dt;if(energyTick>2.2){setEnergy(e=>clamp(e-1,0,100));energyTick=0}}const close=places.filter(q=>q.id!=='station').sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];setNearby(Math.hypot(close.x-p.x,close.z-p.z)<7?close:null);
 const w=canvas.clientWidth*devicePixelRatio,h=canvas.clientHeight*devicePixelRatio;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const horizon=h*.52,sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#8ecde2');sky.addColorStop(1,'#dff3f4');ctx.fillStyle=sky;ctx.fillRect(0,0,w,horizon);const ground=ctx.createLinearGradient(0,horizon,0,h);ground.addColorStop(0,'#b9c0ad');ground.addColorStop(1,'#596257');ctx.fillStyle=ground;ctx.fillRect(0,horizon,w,h-horizon);ctx.fillStyle='rgba(255,255,255,.45)';for(let i=0;i<7;i++){const x=(i*379+now*.006)%w;ctx.beginPath();ctx.ellipse(x,h*.17+(i%3)*25,70,18,0,0,7);ctx.fill()}
 // asphalt road, sidewalks and intersection in strong one-point perspective
 const vanX=w/2-Math.sin(p.a)*w*.12, roadTop=horizon+2, roadHalfTop=w*.055, roadHalfBottom=w*.42;
 const poly=(pts:Array<[number,number]>,fill:string)=>{ctx.fillStyle=fill;ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()};
 poly([[0,horizon],[vanX-roadHalfTop,roadTop],[vanX-roadHalfBottom,h],[0,h]],'#a9aaa2');
 poly([[w,horizon],[vanX+roadHalfTop,roadTop],[vanX+roadHalfBottom,h],[w,h]],'#a9aaa2');
 poly([[vanX-roadHalfTop,roadTop],[vanX+roadHalfTop,roadTop],[vanX+roadHalfBottom,h],[vanX-roadHalfBottom,h]],'#353b3c');
 poly([[vanX-roadHalfTop,roadTop],[vanX-roadHalfTop*.72,roadTop],[vanX-roadHalfBottom*.91,h],[vanX-roadHalfBottom,h]],'#d4d0c5');
 poly([[vanX+roadHalfTop*.72,roadTop],[vanX+roadHalfTop,roadTop],[vanX+roadHalfBottom,h],[vanX+roadHalfBottom*.91,h]],'#d4d0c5');
 // curbs
 ctx.strokeStyle='#f1eee5';ctx.lineWidth=5*devicePixelRatio;ctx.beginPath();ctx.moveTo(vanX-roadHalfTop,roadTop);ctx.lineTo(vanX-roadHalfBottom,h);ctx.moveTo(vanX+roadHalfTop,roadTop);ctx.lineTo(vanX+roadHalfBottom,h);ctx.stroke();
 // lane dashes receding toward the station
 ctx.fillStyle='rgba(244,238,207,.82)';for(let i=0;i<8;i++){const t=i/8,y=roadTop+(h-roadTop)*Math.pow(t,1.75),y2=roadTop+(h-roadTop)*Math.pow(t+.055,1.75),half=roadHalfTop+(roadHalfBottom-roadHalfTop)*Math.pow(t,1.55);poly([[vanX-half*.018,y],[vanX+half*.018,y],[vanX+half*.028,y2],[vanX-half*.028,y2]],'rgba(244,238,207,.82)')}
 // zebra crossing near the station square
 for(let i=-5;i<=5;i++){const yy=h*.63+i*h*.012;const spread=roadHalfTop+(roadHalfBottom-roadHalfTop)*.28;poly([[vanX-spread,yy],[vanX+spread,yy],[vanX+spread*1.04,yy+h*.006],[vanX-spread*1.04,yy+h*.006]],'rgba(242,242,235,.86)')}
 // utility poles, street lamps and greenery
 for(let i=0;i<6;i++){const t=(i+1)/7,y=horizon+(h-horizon)*Math.pow(t,1.45),spread=roadHalfTop+(roadHalfBottom-roadHalfTop)*Math.pow(t,1.3),s=.25+1.15*t;for(const side of [-1,1]){const x=vanX+side*(spread+w*.055*s);ctx.strokeStyle='#414743';ctx.lineWidth=3*s*devicePixelRatio;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-68*s*devicePixelRatio);ctx.stroke();ctx.fillStyle='#263a31';ctx.beginPath();ctx.arc(x-side*7*s,y-62*s*devicePixelRatio,17*s*devicePixelRatio,0,7);ctx.fill();ctx.fillStyle='#54775e';ctx.beginPath();ctx.arc(x-side*12*s,y-70*s*devicePixelRatio,12*s*devicePixelRatio,0,7);ctx.fill();ctx.fillStyle='#f8e3a0';ctx.beginPath();ctx.arc(x,y-69*s*devicePixelRatio,3.5*s*devicePixelRatio,0,7);ctx.fill()}}

 const objects=places.map(q=>({...q,dist:Math.hypot(q.x-p.x,q.z-p.z)})).sort((a,b)=>b.dist-a.dist);for(const q of objects){const center=project(q.x,q.z);if(center.depth<.8)continue;const left=project(q.x-q.w/2,q.z),right=project(q.x+q.w/2,q.z),top=project(q.x,q.z,q.h),bw=Math.abs(right.x-left.x);if(bw>w*2.5)continue;const bh=center.y-top.y,lean=Math.sign(center.x-w/2)*Math.min(bw*.23,70*devicePixelRatio);ctx.fillStyle='rgba(20,28,25,.3)';ctx.beginPath();ctx.ellipse(center.x+lean*.45,center.y,bw*.7,bw*.11,0,0,7);ctx.fill();poly([[center.x-bw/2,top.y],[center.x+bw/2,top.y],[center.x+bw/2+lean,top.y-bw*.12],[center.x-bw/2+lean,top.y-bw*.12]],'#6f756d');ctx.fillStyle=q.color;ctx.fillRect(center.x-bw/2,top.y,bw,bh);poly([[center.x+bw/2,top.y],[center.x+bw/2+lean,top.y-bw*.12],[center.x+bw/2+lean,center.y-bw*.06],[center.x+bw/2,center.y]],'rgba(18,25,23,.38)');ctx.fillStyle=q.accent;ctx.fillRect(center.x-bw*.46,top.y+bh*.12,bw*.92,Math.max(5,bh*.22));ctx.fillStyle='#f8f5ea';ctx.textAlign='center';ctx.font=`700 ${clamp(bw*.12,12*devicePixelRatio,27*devicePixelRatio)}px sans-serif`;ctx.fillText(q.short,center.x,top.y+bh*.28);const floors=Math.max(1,Math.floor(q.h/3));for(let f=0;f<floors;f++){const wy=top.y+(f+.55)*bh/floors;for(let j=-1;j<=1;j++){ctx.fillStyle='rgba(194,224,220,.9)';ctx.fillRect(center.x+j*bw*.25-bw*.085,wy,bw*.17,Math.max(4,bw*.1));ctx.fillStyle='rgba(255,235,174,.35)';ctx.fillRect(center.x+j*bw*.25-bw*.072,wy+bw*.012,bw*.06,Math.max(2,bw*.076))}}ctx.fillStyle='#171d1b';ctx.fillRect(center.x-bw*.1,center.y-Math.max(8,bw*.22),bw*.2,Math.max(8,bw*.22));ctx.fillStyle='rgba(255,255,255,.14)';ctx.fillRect(center.x-bw*.47,top.y+bh*.42,bw*.015,bh*.5)}
 // cinematic road sheen and reticle
 const sheen=ctx.createLinearGradient(0,horizon,0,h);sheen.addColorStop(0,'rgba(255,255,255,.08)');sheen.addColorStop(.55,'rgba(255,255,255,0)');sheen.addColorStop(1,'rgba(12,20,18,.16)');ctx.fillStyle=sheen;ctx.fillRect(0,horizon,w,h-horizon);ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=1.5*devicePixelRatio;ctx.beginPath();ctx.moveTo(w/2-7*devicePixelRatio,h/2);ctx.lineTo(w/2+7*devicePixelRatio,h/2);ctx.moveTo(w/2,h/2-7*devicePixelRatio);ctx.lineTo(w/2,h/2+7*devicePixelRatio);ctx.stroke();frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[]);
 return <main className="game-shell"><canvas ref={canvasRef} className="world" aria-label="武蔵新城駅北口の3D風街歩き画面" onPointerDown={e=>{drag.current=e.clientX;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current!==null){player.current.a+=(e.clientX-drag.current)*.006;drag.current=e.clientX}}} onPointerUp={()=>drag.current=null}/>
 <header className="topbar"><div className="brand"><span className="brand-mark">新</span><div><b>しんじょう さんぽ</b><small>武蔵新城 北口エリア</small></div></div><div className="stats"><span>🪙 <b>{coins.toLocaleString()}</b></span><span>元気 <i><em style={{width:`${energy}%`}}/></i></span></div></header>
 <aside className="quest-card"><p className="eyebrow">TODAY&apos;S WALK</p><h1>北口の4スポットをめぐろう</h1><div className="progress"><span style={{width:`${visited.length/4*100}%`}}/></div><p>{visited.length} / 4 スポット</p><ul>{places.slice(1,5).map(q=><li key={q.id} className={visited.includes(q.id)?'done':''}><span>{visited.includes(q.id)?'✓':'○'}</span>{q.short}</li>)}</ul></aside>
 <aside className="map-card" aria-label="ミニマップ"><div className="map-title"><b>北口駅前</b><span>N ↑</span></div><div className="mini-map"><div className="rail"/><div className="road-h"/><div className="road-v"/>{places.map(q=><span key={q.id} className={`pin pin-${q.id}`} title={q.name}>{q.short}</span>)}<span className="you" style={{left:`${50+player.current.x*1.5}%`,top:`${48-player.current.z*1.1}%`}}>▲</span></div></aside>
 <div className="toast" role="status">{toast}</div>{nearby&&<section className="action-card"><div><small>近くのスポット</small><b>{nearby.name}</b></div><button onClick={interact}><kbd>E</kbd>{nearby.action}</button></section>}<div className="controls"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> 歩く</span><span>ドラッグ 見回す</span><span><kbd>E</kbd> 入る / 調べる</span></div>
 {!started&&<div className="intro"><div className="intro-panel"><p className="eyebrow">MUSASHI-SHINJO WALK</p><h2>いつもの街を、<br/><em>ちょっと冒険に。</em></h2><p>武蔵新城駅・北口から始まる、小さな3D街歩き。気になる店に寄り道しながら、駅前をのんびり歩こう。</p><button onClick={()=>setStarted(true)}>北口からスタート <span>→</span></button><small>キーボード・マウス操作のサンプル版</small></div></div>}</main>
}
