'use client';

import { useCallback, useEffect, useRef, useState } from 'react';

type Place = { id:string; name:string; short:string; x:number; z:number; w:number; h:number; color:string; accent:string; action:string; reward:string };
const places:Place[]=[
{id:'station',name:'JR 武蔵新城駅',short:'北口',x:0,z:18,w:11,h:6,color:'#e9e6df',accent:'#2c8b73',action:'駅を眺める',reward:'南武線の電車がホームへ入ってきた。'},
{id:'mac',name:'マクドナルド 武蔵新城店',short:'McD',x:-12,z:-4,w:8,h:10,color:'#8f211d',accent:'#ffc72c',action:'ポテトを買う  ¥280',reward:'あつあつのポテトを買った！'},
{id:'koban',name:'武蔵新城駅前交番',short:'交番',x:11,z:1,w:5,h:5,color:'#f2f0e8',accent:'#2975b9',action:'道を聞く',reward:'お巡りさんが商店街への道を教えてくれた。'},
{id:'izakaya',name:'駅前餃子酒場',short:'酒場',x:6,z:-12,w:9,h:8,color:'#3c2720',accent:'#f05a3e',action:'餃子を食べる  ¥480',reward:'焼きたて餃子で元気になった！'},
{id:'massage',name:'地下のリラクゼーション',short:'B1',x:6,z:-15,w:7,h:3,color:'#385a52',accent:'#b9e1ca',action:'30分休む  ¥2,000',reward:'足が軽くなった。もう少し歩けそう！'},
{id:'river',name:'小さな眺めスポット',short:'景色',x:-15,z:-23,w:7,h:3,color:'#477c70',accent:'#bce5dd',action:'景色を楽しむ',reward:'風が気持ちいい。街の音が少し遠くなった。'}];
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));

export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null), player=useRef({x:0,z:9,a:Math.PI}), keys=useRef(new Set<string>()), drag=useRef<number|null>(null);
 const [nearby,setNearby]=useState<Place|null>(null),[coins,setCoins]=useState(3000),[energy,setEnergy]=useState(72),[toast,setToast]=useState('北口から街歩きをはじめよう'),[visited,setVisited]=useState<string[]>([]),[started,setStarted]=useState(false);
 const interact=useCallback(()=>{if(!nearby)return;const cost=nearby.id==='mac'?280:nearby.id==='izakaya'?480:nearby.id==='massage'?2000:0;if(cost>coins){setToast('コインが足りません');return}setCoins(c=>c-cost);setEnergy(e=>clamp(e+(nearby.id==='massage'?45:nearby.id==='izakaya'?20:nearby.id==='mac'?10:3),0,100));setToast(nearby.reward);setVisited(v=>v.includes(nearby.id)?v:[...v,nearby.id])},[nearby,coins]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e')interact()},up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[interact]);
 useEffect(()=>{const canvas=canvasRef.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;let frame=0,last=performance.now(),energyTick=0;
 const project=(wx:number,wz:number,wh=0)=>{const p=player.current,dx=wx-p.x,dz=wz-p.z,ca=Math.cos(p.a),sa=Math.sin(p.a),side=dx*ca-dz*sa,depth=dx*sa+dz*ca,scale=canvas.width*.78/Math.max(depth,.1);return{x:canvas.width/2+side*scale,y:canvas.height*.53-wh*scale,depth,scale}};
 const draw=(now:number)=>{const dt=Math.min((now-last)/1000,.04);last=now;const p=player.current,k=keys.current,dir=(k.has('w')||k.has('arrowup')?1:0)-(k.has('s')||k.has('arrowdown')?1:0),turn=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0);p.a+=turn*dt*1.8;p.x+=Math.sin(p.a)*dir*dt*6;p.z+=Math.cos(p.a)*dir*dt*6;p.x=clamp(p.x,-20,20);p.z=clamp(p.z,-27,15);if(dir){energyTick+=dt;if(energyTick>2.2){setEnergy(e=>clamp(e-1,0,100));energyTick=0}}const close=places.filter(q=>q.id!=='station').sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];setNearby(Math.hypot(close.x-p.x,close.z-p.z)<7?close:null);
 const w=canvas.clientWidth*devicePixelRatio,h=canvas.clientHeight*devicePixelRatio;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const horizon=h*.52,sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#8ecde2');sky.addColorStop(1,'#dff3f4');ctx.fillStyle=sky;ctx.fillRect(0,0,w,horizon);const ground=ctx.createLinearGradient(0,horizon,0,h);ground.addColorStop(0,'#b9c0ad');ground.addColorStop(1,'#596257');ctx.fillStyle=ground;ctx.fillRect(0,horizon,w,h-horizon);ctx.fillStyle='rgba(255,255,255,.45)';for(let i=0;i<7;i++){const x=(i*379+now*.006)%w;ctx.beginPath();ctx.ellipse(x,h*.17+(i%3)*25,70,18,0,0,7);ctx.fill()}
 const objects=places.map(q=>({...q,dist:Math.hypot(q.x-p.x,q.z-p.z)})).sort((a,b)=>b.dist-a.dist);for(const q of objects){const center=project(q.x,q.z);if(center.depth<.8)continue;const left=project(q.x-q.w/2,q.z),right=project(q.x+q.w/2,q.z),top=project(q.x,q.z,q.h),bw=Math.abs(right.x-left.x);if(bw>w*2.5)continue;ctx.fillStyle='rgba(30,35,30,.18)';ctx.beginPath();ctx.ellipse(center.x,center.y,bw*.65,bw*.1,0,0,7);ctx.fill();ctx.fillStyle=q.color;ctx.fillRect(center.x-bw/2,top.y,bw,center.y-top.y);ctx.fillStyle=q.accent;ctx.fillRect(center.x-bw*.46,top.y+(center.y-top.y)*.12,bw*.92,Math.max(5,(center.y-top.y)*.22));ctx.fillStyle='#f8f5ea';ctx.textAlign='center';ctx.font=`700 ${clamp(bw*.12,12*devicePixelRatio,27*devicePixelRatio)}px sans-serif`;ctx.fillText(q.short,center.x,top.y+(center.y-top.y)*.28);const floors=Math.max(1,Math.floor(q.h/3));for(let f=0;f<floors;f++){ctx.fillStyle='rgba(205,233,226,.72)';const wy=top.y+(f+.48)*(center.y-top.y)/floors;for(let j=-1;j<=1;j++)ctx.fillRect(center.x+j*bw*.25-bw*.08,wy,bw*.16,Math.max(3,bw*.08))}}
 ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=3*devicePixelRatio;ctx.setLineDash([14*devicePixelRatio,14*devicePixelRatio]);ctx.beginPath();ctx.moveTo(w/2,horizon);ctx.lineTo(w/2,h);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='rgba(255,255,255,.85)';ctx.lineWidth=2*devicePixelRatio;ctx.beginPath();ctx.moveTo(w/2-8,h/2);ctx.lineTo(w/2+8,h/2);ctx.moveTo(w/2,h/2-8);ctx.lineTo(w/2,h/2+8);ctx.stroke();frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[]);
 return <main className="game-shell"><canvas ref={canvasRef} className="world" aria-label="武蔵新城駅北口の3D風街歩き画面" onPointerDown={e=>{drag.current=e.clientX;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current!==null){player.current.a+=(e.clientX-drag.current)*.006;drag.current=e.clientX}}} onPointerUp={()=>drag.current=null}/>
 <header className="topbar"><div className="brand"><span className="brand-mark">新</span><div><b>しんじょう さんぽ</b><small>武蔵新城 北口エリア</small></div></div><div className="stats"><span>🪙 <b>{coins.toLocaleString()}</b></span><span>元気 <i><em style={{width:`${energy}%`}}/></i></span></div></header>
 <aside className="quest-card"><p className="eyebrow">TODAY&apos;S WALK</p><h1>北口の4スポットをめぐろう</h1><div className="progress"><span style={{width:`${visited.length/4*100}%`}}/></div><p>{visited.length} / 4 スポット</p><ul>{places.slice(1,5).map(q=><li key={q.id} className={visited.includes(q.id)?'done':''}><span>{visited.includes(q.id)?'✓':'○'}</span>{q.short}</li>)}</ul></aside>
 <aside className="map-card" aria-label="ミニマップ"><div className="map-title"><b>北口駅前</b><span>N ↑</span></div><div className="mini-map"><div className="rail"/><div className="road-h"/><div className="road-v"/>{places.map(q=><span key={q.id} className={`pin pin-${q.id}`} title={q.name}>{q.short}</span>)}<span className="you" style={{left:`${50+player.current.x*1.5}%`,top:`${48-player.current.z*1.1}%`}}>▲</span></div></aside>
 <div className="toast" role="status">{toast}</div>{nearby&&<section className="action-card"><div><small>近くのスポット</small><b>{nearby.name}</b></div><button onClick={interact}><kbd>E</kbd>{nearby.action}</button></section>}<div className="controls"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> 歩く</span><span>ドラッグ 見回す</span><span><kbd>E</kbd> 入る / 調べる</span></div>
 {!started&&<div className="intro"><div className="intro-panel"><p className="eyebrow">MUSASHI-SHINJO WALK</p><h2>いつもの街を、<br/><em>ちょっと冒険に。</em></h2><p>武蔵新城駅・北口から始まる、小さな3D街歩き。気になる店に寄り道しながら、駅前をのんびり歩こう。</p><button onClick={()=>setStarted(true)}>北口からスタート <span>→</span></button><small>キーボード・マウス操作のサンプル版</small></div></div>}</main>
}
